### ISSUE TITLE
Add support for job strategy: field

### ISSUE THREAD

**Issue by johnpryan** [google/mono_repo.dart#309]
Jobs can have a `strategy:`. For example, the [`fail-fast`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) strategy can be used to disable behavior where one failed test cancels all the remaining jobs:

```yaml
strategy:
  fail-fast: false
```

**Comment by kevmoo** [comment]
More details please?

**Comment by johnpryan** [comment]
This comes up in CI runs where one job is expected to fail, but we would still like to run the others: https://github.com/dart-lang/samples/pull/88/checks?check_run_id=2004793133

**Comment by kevmoo** [comment]
i think this is a bug. We should copy what Alex did w/ the default Dart action.

CC @jakemac53

**Comment by jakemac53** [comment]
This is because there are multiple "stages" defined - the behavior of stages is such that they only run if previous stages succeeded.

There isn't any other functionality provided by them, so I would just collapse your jobs all to be under a single stage. See as an example here https://github.com/dart-lang/samples/blob/master/ffi/hello_world/mono_pkg.yaml#L11.

In general though we do this to be good citizens in terms of CI usage - especially previously with travis we had a shared pool of workers for all dart-lang repos and not running tests when analysis failed as an example helps decrease usage. I don't know how true that is with github actions or not.
