### ISSUE TITLE
Pin hashes for dependencies

### ISSUE THREAD

**Issue by sealesj** [google/mono_repo.dart#381]
While using github workflows, we need to specify a commit for the action (see [go/github-actions#actions](http://goto.google.com/github-actions#actions)). In the test repo of dart-lang, this dependency commit pinning needs to be completed. However since the mono repo tool is used to handle those dependencies, the tool should be updated to do the pinning. Context for this change comes from this pull request: https://github.com/dart-lang/test/pull/1699

**Comment by kevmoo** [comment]
I guess we could add an option for this.

Hrm.

We could just have a setting in `mono_repo.yaml` to let folks hard-code versions. PRs welcome!

**Comment by kevmoo** [comment]
Thoughts @jakemac53 @natebosch ?

**Comment by jakemac53** [comment]
If we believe that pinning these dependencies is the correct thing to do, I would argue we should just always do that, and not add additional complexity with an option. This tool is really just for us anyways, and we benefit from consistency here.

**Comment by kevmoo** [comment]
Requiring mono_repo to roll for every desired "dot" release is (as the kids say) "a big lift". We should ponder a model here where we can move versions of things forward without having to touch mono_repo

Maybe mono_repo generate could have a "latest" option or similar?

**Comment by natebosch** [comment]
+1 for having fewer options and just picking what we want the behavior to be always.

I like the idea of finding the latest versions each time the tool runs. I don't think it's a huge problem if it means we pick up a dependency on a working network since regenerating github workflows is only useful when you will upload a PR anyway.

**Comment by kevmoo** [comment]
The *only* issue is that there could be breaking changes that affect what we generate.

So auto-magically always getting latest could be a problem. A flag for `mono_repo generate --latest` or similar could work

**Comment by natebosch** [comment]
What would we use when we don't pass the `--latest` flag? A hardcoded set of defaults like we use today?

When would we choose to run without `--latest`? Would doing so downgrade us to earlier versions than we had been using?

**Comment by devoncarew** [comment]
I think the issue here is that two entities want to control the actions versions in the workflow files? In this case it us (based on feedback from the scorecards / `scorecards-analysis.yml` system) and mono_repo? We have a similar issue with dependabot and momo_repo - they both want to manage the actions versions in the workflow files.

One solution here would be for mono_repo to recognize when something else may be managing the action versions. So, if it detects either a `dependabot.yaml` file, or a `scorecards-analysis.yml` file, it could read the current actions versions from dart.yml before regenerating that file. If neither file exists, or if dart.yml hadn't yet been generated, mono_repo could just use its current default versions.

This would let mono_repo play well with both the scorecard system and with dependabot.

(from a separate thread, athomas and I came to the conclusion that dependabot would do the right thing here wrt upgrading SHAs; we'd write a dart.yml file w/ an `@1.3` version; the scorecare would want us to replace w/ a SHA; and, when a 1.4 version came out, dependabot would recognize that we're using a SHA, and write in the appropiate SHA for `@1.4`)

**Comment by drewroengoogle** [comment]
Would it make sense to start out by only changing the hardcoded versions to hashes and nothing else? From my understanding, it seems like when an action is currently updated it is manually updated anyway, so I'm wondering if there would be any additional work created by using hashes if you'd like to update an action's version in the future.

**Comment by jakemac53** [comment]
That is what I would suggest yes as its the easiest solution and not really worse than what we have today. We can always change how this is done later.

**Comment by kevmoo** [comment]
That's fine with me.

**Comment by drewroengoogle** [comment]
Sorry for a late follow up to this, but I opened a PR to change the version numbers to hashes to tackle this issue! Out of curiosity, how often are versions published to pub.dev?

**Comment by kevmoo** [comment]
This has been done!
